### ISSUE TITLE
License

### ISSUE THREAD

**Issue by armintoepfer** [yangao07/abPOA#1]
Hi!

Great work. Any chance that you would consider relicensing to a more permissive license or offer a one time relicensing?

Thank you!

**Comment by yangao07** [comment]
Hi,
Thanks for your interest in abPOA!

What is your purpose of using abPOA?
I am actually not very familiar with all those license types.
 Are you referring to the MIT license?

Yan

**Comment by armintoepfer** [comment]
I intend to benchmark it for various use cases, where I'm currently using SPOA, and then possible integrate it into PacBio software as an alternative to SPOA. As we use BSD-3, I'm not allowed to integrate GPL software. MIT is an example that would be good. Examples for MIT software: SPOA and minimap2.

**Comment by yangao07** [comment]
I just changed it to MIT.
Do you need the file in the release also be changed?

**Comment by armintoepfer** [comment]
No that's fine, I'll get it from git directly. Thank you very much. Expect bug reports flying in, in case we find issues :)

**Comment by yangao07** [comment]
Sure.
Bug reports and any kinds of suggestions are welcome!
