### ISSUE TITLE
Error in logic for read ID labeling at source node

### ISSUE THREAD

**Issue by NatPRoach** [yangao07/abPOA#15]
Hello,
I'm working on binding abPOA in nim for a project I'm working on and I think I stumbled upon an error in the logic of the function `abpoa_add_subgraph_alignment`. Specifically related to the labeling of read IDs in the source node. At several points in this function there's a line:
`if (last_id == beg_node_id && beg_node_id != ABPOA_SRC_NODE_ID) w = 0, add = 0; else w = 1, add = 1;`

I _think_ based on my understanding of the desired result here, that the `beg_node_id != ABPOA_SRC_NODE_ID` should be `beg_node_id == ABPOA_SRC_NODE_ID`.

I could be wrong, if it's intended behavior to add weights and read_IDs at the source node then please correct me.
Thank you for the tool by the way it's quite impressive work.

**Comment by yangao07** [comment]
Hi Nathan,

I did intend to add the read id and edge weight to the virtual start/source node in abpoa graph.
Otherwise, it will lead to a wrong result sometimes in the consensus calling step.

Yan

**Comment by yangao07** [comment]
Also, thanks for your interest in abPOA, and hope it works well in your project!
Let me know if you meet any issues in the future.

Yan

**Comment by NatPRoach** [comment]
Hi Yan,
Thanks for the prompt response! Apologies for my misunderstanding!

In that case is there a reason that the first sequence inserted in to the graph doesn't get its read ID added to the source node? Seems like when the graph is empty and the first sequence is added in the source node doesn't get labeled with the first read ID. Such that if aligning two identical short sequences to one another the readIDs look like the following:

```
nodeID - 0
readIdsN - 1
  readID - 2

nodeID - 1
readIdsN - 0

nodeID - 2
readIdsN - 1
  readID - 3

nodeID - 3
readIdsN - 1
  readID - 3

nodeID - 4
readIdsN - 1
  readID - 3

nodeID - 5
readIdsN - 1
  readID - 3

nodeID - 6
readIdsN - 1
  readID - 3

nodeID - 7
readIdsN - 1
  readID - 3

nodeID - 8
readIdsN - 1
  readID - 3

nodeID - 9
readIdsN - 1
  readID - 3

nodeID - 10
readIdsN - 1
  readID - 3

nodeID - 11
readIdsN - 1
  readID - 3

nodeID - 12
readIdsN - 1
  readID - 3

nodeID - 13
readIdsN - 1
  readID - 3
```

**Comment by yangao07** [comment]
I checked the code and found that there is indeed a bug related to the read id assignment.
Fixed it in the latest commit. Now the source id will be assigned with all the read ids.
Thanks for catching and pointing out this bug!
Yan

**Comment by NatPRoach** [comment]
Awesome, thank you for the quick turnaround!
No problem at all!
