### ISSUE TITLE
pip install fails on multiple machines

### ISSUE THREAD

**Issue by christopher-vollmers** [yangao07/abPOA#19]
Hi,

I've been trying to install pyabpoa and on multiple machine the install fails with

`src/abpoa_align.c:6:10: fatal error: 'abpoa_seq.h' file not found
    #include "abpoa_seq.h"
             ^~~~~~~~~~~~~
    2 warnings and 1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1`

Any idea what's going on there?

Thank you,
Chris

**Comment by alicecsq** [comment]
Hi,
I also got a very similar error when I tried to pip install pyabpoa. 

src/abpoa_align.c: At top level:
    src/abpoa_align.c:6:10: fatal error: abpoa_seq.h: No such file or directory
     #include "abpoa_seq.h"
              ^~~~~~~~~~~~~
    compilation terminated.
    error: command '/usr/bin/gcc' failed with exit code 1

Can you please help?

Thank you!
Alice

**Comment by yangao07** [comment]
Hi Chris and Alice,

Sorry about the installation error.
It should be fixed now, please try re-install pyabpoa with `pip install pyabpoa==1.1.4`.
Let me know if you still get any error messages.

Yan

**Comment by alicecsq** [comment]
Hi Yan, 
       Thank you so much! This works now.

Best,
Alice
