### ISSUE TITLE
Feature request: Allow specification of full scoring matrix

### ISSUE THREAD

**Issue by glennhickey** [yangao07/abPOA#20]
Only a match score and mismatch penalty are available now.  Would it be possible to allow specification of a full matrix?  We would like to be able to, for example, use the default lastz scoring matrix referred to here: http://www.bx.psu.edu/~rsharris/lastz/README.lastz-1.04.03.html#options_scoring

As far as I can tell, this is just requires additional interface given that a [full matrix seems to be used internally](https://github.com/yangao07/abPOA/blob/master/src/abpoa_align.c#L76)?  Personally, I'm more interested in doing this via the C API than the command line, but I'm sure other users would like the option there too.  Thanks!

**Comment by glennhickey** [comment]
On a slightly related note:  I've noticed that abpoa can give quite different results when I do things like scale all the parameters up by the same value.  Is this by design?  Are there any maximums or hidden paramters that can affect this?

**Comment by yangao07** [comment]
1. abPOA allows three gap penalty modes: convex, affine and linear.
So match(-M), mismatch(-X), gap-open(O), and gap-extension(E) all can be specified by users.
So how come
> Only a match score and mismatch penalty are available now.

2. 
> scale all the parameters up by the same value

How did you scale the parameters? Did you only scale the match/mismatch or all the scoring parameters?

Yan

**Comment by yangao07** [comment]
> Only a match score and mismatch penalty are available now. Would it be possible to allow specification of a full matrix? We would like to be able to, for example, use the default lastz scoring matrix referred to here: http://www.bx.psu.edu/~rsharris/lastz/README.lastz-1.04.03.html#options_scoring
> 
> As far as I can tell, this is just requires additional interface given that a [full matrix seems to be used internally](https://github.com/yangao07/abPOA/blob/master/src/abpoa_align.c#L76)? Personally, I'm more interested in doing this via the C API than the command line, but I'm sure other users would like the option there too. Thanks!

This should be easy to update. I will work on that.

**Comment by glennhickey** [comment]
Thanks!

About the scaling being inconsistent:  I was unable to reproduce an example to send you.  I must have been mistaken when I thought I saw this happen.  If I can find an example, I'll send it right away.  In the meantime, sorry!

**Comment by yangao07** [comment]
Check out the latest commit of abpoa (v1.2.2), which now takes a new parameter `-t score.matrix`.

**Comment by glennhickey** [comment]
Thanks!!!
