### ISSUE TITLE
Option to switch off logging messages

### ISSUE THREAD

**Issue by glennhickey** [yangao07/abPOA#21]
Would it be possible to add an option to disable the logging messages to stderr?  I think they all come from `err_func_format_printf()` and start to dominate the logs from my client code that calls abpoa repeatedly.  Thanks so much!

**Comment by yangao07** [comment]
How abouth simply `abpoa in.fa > out.fa 2> /dev/null`?
Do this solve your problem?

**Comment by glennhickey** [comment]
No, I'm using the abpoa api in my own executable where abpoa gets run (simultaneously in different threads) thousands of times.  So my own log messages, which get output to stderr, are buried under thousands of abpoa messages.

**Comment by yangao07** [comment]
OK, I see.
I just removed those log msg in the recent commit. 
Please check it out.

**Comment by glennhickey** [comment]
Thanks so much!
