### ISSUE TITLE
abPOA seems unstable with HOX scoring matrix

### ISSUE THREAD

**Issue by glennhickey** [yangao07/abPOA#22]
I noticed abPOA returning some bizarre alignments when running with a scoring matrix.  In my Cactus output, it would lead to a lot of cases of identical sequences getting useless gaps (a T inserted, then a T deleted a few bases later, ex).

I tried to pull out an example to reproduce on the command line.  Instead of the wrong alignment, it just crashes (hopefully it's the same underlying problem).  It runs okay without `-t`
```
wget http://public.gi.ucsc.edu/~hickey/debug/abpoa_fail_may31.fa
./abPOA/bin/abpoa abpoa_fail_may31.fa -m 0 -r 1  -t abPOA/HOXD70.mtx -N
[simd_abpoa_align_sequence_to_subgraph] Error in cg_backtrack. (5)
```
In cactus, switching on the anchoring with disableSeeding=0 fixes many of these cases.  But I am worried there is an underlying issue (perhaps numerical?) with scoring matrices that makes it unstable for larger subproblems.

**Comment by yangao07** [comment]
I also noticed this. 
It is mainly because the gap-open and gap-extension penalty are not set accordingly.
I should probably throw out an error message instead of just let it go all the way to the alignment error.

**Comment by glennhickey** [comment]
Thanks!  But I still get the same `Error in cg_backtrack` with the above commands.  It does now run through without the -N, but it still seems like there's an issue?

**Comment by glennhickey** [comment]
Actually, there is a small difference in the error message numbers.  With 1.2.2 I get
```
./abPOA/bin/abpoa abpoa_fail_may31.fa -m 0 -r 1  -t abPOA/HOXD70.mtx  -N
[simd_abpoa_align_sequence_to_subgraph] Error in cg_backtrack. (5)
```
and 1.2.3
```
./abPOA/bin/abpoa abpoa_fail_may31.fa -m 0 -r 1  -t abPOA/HOXD70.mtx  -N
[simd_abpoa_align_sequence_to_subgraph] Error in cg_backtrack. (2)
```

**Comment by glennhickey** [comment]
Will just add that 1.2.3 does improve accuracy a bit over 1.2.2, but does not seem to fix the issue.  On one test I've been looking at, I get:
1.2.2 or 1.2.3 with seeding enabled: ~690 errors
1.2.2 with no seeding: ~10000 errors
1.2.3 with no seeding: ~5500 errors

To me, this is evidence (along with that crash) that there are still problems in abpoa, likely related to overflows from the larger scoring parameters.

**Comment by yangao07** [comment]
You are right, a similar bug still exists, also related to the match/mismatch score, :(.
Let me fix it. 
Apologize for the inconvenience.

Yan

**Comment by glennhickey** [comment]
Thanks again for your fast response!  This version fixes the crash, but unfortunately only reduces the overall number of wrong alignments I'm seeing by a small amount.  It really does continue to look like a numerical stability issue.  Do these scoring parameters just lead to scores that are too big to fit in the simd registers you are using?  Is it possible to estimate the maximum matrix size I can safely use with them (right now I'm using 10kb) ?

I will try to find an example on the command line to reproduce one of these issues.

**Comment by yangao07** [comment]
The largest number that fits in the SIMD register is int32, so it should be OK.
Even for 10kb-long sequences (I guess you're talking about the length), they should be fine.

Yes, giving me an example will definitely help!

Yan

**Comment by glennhickey** [comment]
Oops, this was my fault.  I updated to the latest abPOA but did not change my client code to initialize `max_mat` and `min_mis`, so was not properly using your fix.  Correcting this, I get the expected results on my tests:
* better accuracy with the matrix than the default parameters
* better accuracy without seeding (instead of the other way around)

Sorry about the confusion, and thanks again!
