### ISSUE TITLE
Can't install versions later than 1.0.2 using pip on Ubuntu 20.04 LTS in Docker

### ISSUE THREAD

**Issue by hcstubbe** [yangao07/abPOA#23]
On Ubuntu 20.04 LTS (and on Debian) I cannot freshly (i.e. without earlier versions installed) install the later versions of pyabpoa using pip. The only workaround is to install version 1.0.2 and then update. This makes installing pyabpoa in a docker image extremely hard.

Error message:

> #16 1.287 Collecting pyabpoa==1.2.4
#16 1.411   Downloading pyabpoa-1.2.4.tar.gz (138 kB)
#16 1.604 ERROR: Files/directories not found in /tmp/pip-install-6dwget1n/pyabpoa/pip-egg-info

Any idea how to fix this?

Thank You!

**Comment by yangao07** [comment]
This is weird, I can not reproduce your error on my machine.
Does installing it from the source files work for you?https://github.com/yangao07/abPOA/tree/master/python#install-pyabpoa-from-source

Yan

**Comment by hcstubbe** [comment]
Hey Yan,

did You try to install it on Ubuntu without a previous installations of pyabpoa? When I run the docker build with this [Dockerfile](https://github.com/hcstubbe/r2c2_docker/blob/main/Dockerfile), later versions fail, but not version 1.0.2. This also happens on my WSL2 Ubuntu 20.04 LTS on Windows 10.
Installing from source works, but my script (using [C3POa](https://github.com/rvolden/C3POa)) fails when using later versions than 1.0.6 (in fact, it only works with 1.0.6 - I haven't worked out yet, why this happens).
My workaround is to first install 1.0.2 and then install 1.0.6.

Thank You for looking into this!

All the best
Hans

**Comment by yangao07** [comment]
Hi Hans,
I did reproduce this error on a machine that has no previous version of pyabpoa.
It seems like is caused by the absence of cython.
So you need to mannully
```
pip install cython
```
and then 
```
pip install pyabpoa==1.2.4
```
This works for me.
Let me know if this fixes your issue.

Yan

**Comment by hcstubbe** [comment]
Hi Yan,

thank You for looking into this! Manually installing cython before pyabpoa works!

All the best
Hans
