### ISSUE TITLE
Change in abpoa_msa function signature

### ISSUE THREAD

**Issue by adcosta17** [yangao07/abPOA#38]
Hi, 

I have abPOA integrated within another tool and I'm using it for consensus calling. I've been using the abpoa_msa function as previously described in the example.c file. With the latest version of abPOA I noticed that the signature for this function has changed, mainly it no longer allows for a consensus to be saved to a string in memory, but now expects only a C FILE pointer to write the output to file or stdout. 

Is it possible to bring back or add an option to save the concensus in memory with the latest version? 

Thanks

**Comment by glennhickey** [comment]
I ran into this too...  it moved into [abpoa_cons_t](https://github.com/yangao07/abPOA/blob/5140da18e0b07554b41746928e4e7ec5b414ac77/src/abpoa.h#L102-L112) which gets made by apoa_msa via the [abpoa_t](https://github.com/yangao07/abPOA/blob/5140da18e0b07554b41746928e4e7ec5b414ac77/src/abpoa.h#L133) input. You can leave the FILE pointer NULL.

**Comment by yangao07** [comment]
@glennhickey is right, [abpoa_cons_t](https://github.com/yangao07/abPOA/blob/5140da18e0b07554b41746928e4e7ec5b414ac77/src/abpoa.h#L102-L112) includes a set of variables related to consensus calling result. 
For FILE point, leave it as NULL if you want to store consensus in variables, example.c shows how to use it.

**Comment by adcosta17** [comment]
I made the changes and its working well. 
Thanks!
