### ISSUE TITLE
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'output.json'

### ISSUE THREAD

**Issue by kcjavier21** [yangao07/abPOA#43]
I'm getting this error while installing pyabpoa using pip. Any solution for this? I tried everything to search for solutions but nothing worked.

![image](https://user-images.githubusercontent.com/64310834/227690139-99f3dc02-6b5d-407b-9954-0c0f506e966a.png)

**Comment by yangao07** [comment]
Looks like you are using windows system?
Since pyabpoa is based on abPOA, which is Linux-based, they may not be installed in windows.

**Comment by kcjavier21** [comment]
Alright, will try that out. Will update you if it works. Thank you!

**Comment by kcjavier21** [comment]
Tried in Ubuntu. Same result

![image](https://user-images.githubusercontent.com/64310834/230252539-6e7eee28-5ad7-4a7e-bde7-69ee0eace12d.png)

**Comment by kcjavier21** [comment]
Gonna close this issue. Do the following instead https://github.com/yangao07/abPOA/issues/45.
