### ISSUE TITLE
Cython is already installed but I keep getting error

### ISSUE THREAD

**Issue by kcjavier21** [yangao07/abPOA#45]
I'm trying to install the package by using the command
`make install_py`

But then I'm getting error about cython, which is already installed.

How can I fix this? Thank you!

![image](https://user-images.githubusercontent.com/64310834/230130459-f8bbc5c8-b289-4c83-9041-6ee4fd908221.png)

**Comment by yangao07** [comment]
I guess the cython was not installed in the same place as your current python?
Can you try which common for python and cython?

**Comment by kcjavier21** [comment]
Oh yeah, it's on a different folder. How can I install it on the same folder as python? 

I just insert `pip install cython` for installing it. Can I just copy cython and paste it on the folder where python is located?

![image](https://user-images.githubusercontent.com/64310834/230249929-80153c92-283c-4b65-95a3-89f385352796.png)

**Comment by yangao07** [comment]
I think you should be able to install pyabpoa after "pip install cython".

**Comment by kcjavier21** [comment]
I still can't :(

![image](https://user-images.githubusercontent.com/64310834/230252212-c58705b3-4173-4e43-8e0f-ff063b8fdeb4.png)

**Comment by yangao07** [comment]
OK, do you have python under your '.local/bin' folder?
If so, you should use that python for installation.

**Comment by kcjavier21** [comment]
Copied python in ./local/bin which is the same as cython. Uninstalled and reinstalled cython. Same result :(

![image](https://user-images.githubusercontent.com/64310834/230256543-17e370e8-daaf-41d0-b6c0-1eeeabbcc3d1.png)

**Comment by kcjavier21** [comment]
Should I also move pip in /.local/bin?

**Comment by yangao07** [comment]
What's the output of "python -c ```import Cython"``` on your machine?

**Comment by kcjavier21** [comment]
That's weird. It says no module named 'Cython'

![image](https://user-images.githubusercontent.com/64310834/230266702-11775c3a-7a58-447a-8059-082a105ecf4e.png)
pip

**Comment by yangao07** [comment]
OK, this is the reason.
You need to install cython with this specific python.
Maybe try ```python -m pip install cython```

**Comment by kcjavier21** [comment]
Okay. But should I uninstall the cython first and then reinstall using that command?

**Comment by yangao07** [comment]
It doesn't matter.

**Comment by kcjavier21** [comment]
Oh, it worked! But I got new error.

![image](https://user-images.githubusercontent.com/64310834/230267701-f886d70d-6168-450f-85a1-6d8850f5e250.png)

**Comment by yangao07** [comment]
How about ```python -m pip install .```?

**Comment by kcjavier21** [comment]
It gives the same error when I run 'pip install pyabpoa' 

![image](https://user-images.githubusercontent.com/64310834/230268649-c6c6611c-10ec-4c68-91bd-5c863e84053d.png)

![image](https://user-images.githubusercontent.com/64310834/230268701-b2519769-dd06-4307-bad8-680918f590a0.png)

**Comment by yangao07** [comment]
I guess you downloaded the zipped repo from abPOA github homepage directly.
Try using the release link:
wget https://github.com/yangao07/abPOA/releases/download/v1.4.1/abPOA-v1.4.1.tar.gz
tar -zxvf abPOA-v1.4.1.tar.gz && cd abPOA-v1.4.1

**Comment by kcjavier21** [comment]
OMG! It worked! Thank you so muuuch!
![image](https://user-images.githubusercontent.com/64310834/230270552-60cb104f-4f3d-43f6-b738-ee3f168caa57.png)
