### ISSUE TITLE
Expected behavior of the extension alignment mode.

### ISSUE THREAD

**Issue by ctsa** [yangao07/abPOA#49]
Thanks for publishing this method!

I'm trying to clarify whether the 'extension' alignment mode is supposed to behave like an 'overlap' style of scoring, allowing for one free end for both text and query. 

To illustrate, if I have two sequences in `ext1.fa`:
```
>1
ACGTTGCCCGTTAAGGGT
>2
CCGTTAAGGGTATGTCCC
```

Aligning these using local alignment mode happens to give an extension/overlap style alignment in this case:
```
[main] CMD:  abpoa -m1 -r1 ext1.fa
>1
ACGTTGCCCGTTAAGGGT-------
>2
-------CCGTTAAGGGTATGTCCC
```

...but switching to the extension scoring mode, it is harder to interpret what this mode is doing:
```
[main] CMD:  abpoa -m2 -r1 ext1.fa
>1
ACGTT-------------GCCCGTTAAGGGT
>2
CCGTTAAGGGTATGTCCC-------------
```

All examples are from the current main (d2e0186963b5d8418dcc86f4154a4703fbce94dd).

Can you clarify what the expected constraints for extension mode are? Is any configuration of abPOA constrained to give the 'overlap' style I show above?

**Comment by yangao07** [comment]
The extension mode is meant to find the right-most position where the alignment score is max.
So for your example, the score is the max for "ACGTT" and "CCGTT". 
It will decrease for any additional bases. So all the remaining parts are unaligned.

For your purpose of finding overlap, I guess the local mode may just work.

**Comment by ctsa** [comment]
Thanks for clarifying this..

**Comment by ctsa** [comment]
With some more trials it looks like a semi-global mode would be ideal for the case I have in mind... is this something you've been considering for abPOA?

**Comment by yangao07** [comment]
I think semi-global is possible to be added for abPOA, since it is similar to local.
I have been thinking about this mode but didn't see scenarios that it could be used.
So what is your task here?

**Comment by ctsa** [comment]
Thanks @yangao07!

As a first step I've run into some instability during initial testing, I'll file a separate issue for this case to see if we can figure out wether this is fixable. If we get that working later with local mode then I'd be happy to go into more detail on our case and how semi-global would (theoretically) be a better fit.
