### ISSUE TITLE
Segmentation fault error 

### ISSUE THREAD

**Issue by Goatofmountain** [yangao07/abPOA#52]
Hi Yan,
I want to use abPOA with my ONT data to make multisequence alignment, but it comes out with a "Segmentation fault" error, with empty output. 
Here is my cmd
`abpoa -r 1 -S Test.fasta > Test.MSA.fasta`
and my test data file 
[Test.zip](https://github.com/yangao07/abPOA/files/12313900/Test.zip)

I wonder if abPOA is not fit for data with too many long read sequence when making MSA ? 

Thank you. 
KT

**Comment by yangao07** [comment]
Seems like your sequences are very long and divergent.
I didn't see the seg fault but abpoa uses more than 512G memory even with the seeding mode enabled.
For this case, I suggest you do some pre-processing and split the sequences into smaller regions, and apply abpoa for each region.

**Comment by Goatofmountain** [comment]
Thank you for your suggestion. 
After splitting the reads, the program worked fine, and the result was similar to what I expected. 
Useful tool, thanks again !
