### ISSUE TITLE
cython is required at build time but not install time

### ISSUE THREAD

**Issue by tillea** [yangao07/abPOA#56]
Hi,
as per some [Debian bug report](https://bugs.debian.org/1057980) cython is required to build the package but on the installed system it is not really needed.  I've fixed the Debian bug with this [patch](https://salsa.debian.org/med-team/abpoa/-/blob/master/debian/patches/no_install_depends_cython.patch) you might like to take over in your next release.
Kind regards, Andreas.

**Comment by yangao07** [comment]
Thanks for pointing this out! I have made the change in the latest version.

**Comment by tillea** [comment]
Am Tue, Dec 12, 2023 at 07:18:26PM -0800 schrieb Yan Gao:
> Thanks for pointing this out! I have made the change in the latest version.

Thanks a lot for your quick response, Andreas.
