### ISSUE TITLE
abPOA fails to capture difference in prefix

### ISSUE THREAD

**Issue by TanyaDvorkina** [yangao07/abPOA#57]
Hi,

Thank you for developing abPOA!

I am trying to use abPOA to build consensus and cluster short TR sequences (~40-70bp in length). I've noticed that if the difference in sequences is in prefix, then abPOA identifies only one cluster instead of two.

I generated three different dataset of 20 reads using this function:

```
def generate_subreads(num, where = "start"):
    seqs = []
    repeat = "CTAT"
    insertion="TCTA"
    if where == "start":
        for i in range(num//2):
            seqs.append(SeqRecord(Seq(insertion + repeat*15), id = str(i), name= str(i), description=""))
    elif where == "middle":
        for i in range(num//2):
            seqs.append(SeqRecord(Seq(repeat*8 + insertion + repeat*7), id = str(i), name= str(i), description=""))
    else:
        for i in range(num//2):
            seqs.append(SeqRecord(Seq(repeat*15 + insertion), id = str(i), name= str(i), description=""))

    for i in range(num//2):
        seqs.append(SeqRecord(Seq(repeat*15), id = str(num//2 + i), name= str(num//2 + i), description=""))

    return seqs
```

and run:
`aligner.msa(seqs, out_cons=True, out_msa=True, max_n_cons=2, min_freq=0.3)`

and here is the output of the aligner.msa on these datasets:
[synthetic_output.txt](https://github.com/yangao07/abPOA/files/13704340/synthetic_output.txt)

Is there a problem with abpoa algorithm on such corner case?

Thank you,
Tatiana

**Comment by yangao07** [comment]
Thanks for the feedback, this is a bug related to this corner case.
Should have been fixed in the latest commit 58e4a99.
Also, since this function is not thoroughly tested, let me know when you see anything weird in the future.
