### ISSUE TITLE
cons_algrm via pyabpoa

### ISSUE THREAD

**Issue by aistBMRG** [yangao07/abPOA#76]
Hi, I am running abpoa via python binding. I am interested in accessing the cons_algrm variable, setting to the most common base. Would it be possible to clarify how to set this up? Fyi, my current commands are as follows:

```
import pyabpoa as pa
a = pa.msa_aligner()
a.msa(seqs, out_cons=True, out_msa=True).cons_seq[0]
```

Thanks. 
Dieter

**Comment by yangao07** [comment]
Hi, this is quite easy to add for pyabpoa.
You can build/install it using the latest source code.
Pypi should be available in the next released version.
